using System.Linq;
using Content.Shared._BF.TTS;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminAnnounceWindow : DefaultWindow
    {
        [Dependency] private readonly ILocalizationManager _localization = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

        private readonly List<TTSVoicePrototype> _voicePrototypes;

        public AdminAnnounceWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Announcement.Placeholder = new Rope.Leaf(_localization.GetString("admin-announce-announcement-placeholder"));
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-station"));
            AnnounceMethod.SetItemMetadata(0, AdminAnnounceType.Station);
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-server"));
            AnnounceMethod.SetItemMetadata(1, AdminAnnounceType.Server);
            AnnounceMethod.OnItemSelected += AnnounceMethodOnOnItemSelected;
            Announcement.OnKeyBindUp += AnnouncementOnOnTextChanged;

            _voicePrototypes = _prototypeManager
                .EnumeratePrototypes<TTSVoicePrototype>()
                .Where(o => o.ID.Contains("Announcer"))
                .OrderBy(o => Loc.GetString(o.Name))
                .ToList();

            for (var i = 0; i < _voicePrototypes.Count; i++)
            {
                VoiceSelector.AddItem(Loc.GetString(_voicePrototypes[i].Name), i);
            }

            VoiceSelector.OnItemSelected += args =>
            {
                VoiceSelector.SelectId(args.Id);
            };
        }

        public ProtoId<TTSVoicePrototype> GetVoice()
        {
            return _voicePrototypes.TryGetValue(VoiceSelector.SelectedId, out var proto)
                ? proto
                : _voicePrototypes.First();
        }

        private void AnnouncementOnOnTextChanged(GUIBoundKeyEventArgs args)
        {
            AnnounceButton.Disabled = Rope.Collapse(Announcement.TextRope).TrimStart() == "";
        }

        private void AnnounceMethodOnOnItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            AnnounceMethod.SelectId(args.Id);
            Announcer.Editable = ((AdminAnnounceType?)args.Button.SelectedMetadata ?? AdminAnnounceType.Station) == AdminAnnounceType.Station;
        }
    }
}
