- type: job
  id: LinerBoatswain
  name: boatswain
  description: The boatswain.
  playTimeTracker: JobLinerBoatswain
  weight: 10
  startingGear: DoctorGear
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
