- type: job
  id: LinerCaptainAssistant
  name: captain assistant
  description: The captain assistant.
  playTimeTracker: JobLinerCaptainAssistant
  weight: 20
  startingGear: DoctorGear
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
