- type: job
  id: LinerCaptainAssistant
  name: ассистент капитана
  description: Вторая и, скорее всего, первая рука капитана. Следит за персоналом, чтоб никто не отлынивал!
  playTimeTracker: JobLinerCaptainAssistant
  weight: 20
  startingGear: LinerCaptainAssistantGear
  icon: "JobIconHeadOfPersonnel"
  requirements:
  - !type:DepartmentTimeRequirement
    department: Booster
    time: 54000 # 15 hours
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: LinerCaptainAssistantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoP
    back: ClothingBackpackHOPFilled
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHatHopcap
    id: HoPPDA
    gloves: ClothingHandsGlovesHop
    ears: ClothingHeadsetAltCommand
    belt: ClothingBeltSheathFilled
  innerClothingSkirt: ClothingUniformJumpskirtHoP
  satchel: ClothingBackpackSatchelHOPFilled
  duffelbag: ClothingBackpackDuffelHOPFilled
