- type: job
  id: LinerCaptain
  name: liner captain
  description: The captain of the lux liner.
  playTimeTracker: JobLinerCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Booster
      time: 54000 # 15 hours
  weight: 20
  startingGear: DoctorGear
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
