- type: job
  id: LinerCaptain
  name: капитан
  description: Крутой капитан с большим стажем. К сожалению, он очень сильно занят.
  playTimeTracker: JobLinerCaptain
  icon: "JobIconCaptain"
  requirements:
    - !type:DepartmentTimeRequirement
      department: Booster
      time: 54000 # 15 hours
  weight: 20
  startingGear: LinerCaptainGear
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: LinerCaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCapFormal
    back: ClothingBackpackCaptainFilled
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHatCapcap
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    outerClothing: ClothingOuterArmorCaptainCarapace
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  innerClothingSkirt: ClothingUniformJumpskirtCapFormalDress
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled
