- type: job
  id: LinerOfficer
  name: officer
  description: The officer.
  playTimeTracker: JobLinerOfficer
  startingGear: DoctorGear
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
