- type: job
  id: LinerSanta
  name: Santa Clause
  description: Santa Clause.
  playTimeTracker: JobLinerSanta
  startingGear: DoctorGear
  supervisors: job-supervisors-service
  canBeAntag: false
  access:
  - Service
  - Maintenance
  - Bar
  - Kitchen
  extendedAccess:
  - Hydroponics
