- type: job
  id: LinerSeniorTech
  name: главный техник
  description: Залотает неожиданную дырку. Следите, чтоб он не выпил всю водку, а то Вам не достанется.
  playTimeTracker: JobLinerSeniorTech
  weight: 20
  startingGear: LinerSeniorTechGear
  icon: "JobIconChiefEngineer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Brig
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: LinerSeniorTechGear
  equipment:
    head: ClothingHeadHatHardhatWhite
    jumpsuit: ClothingUniformJumpsuitSeniorEngineer
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    id: SeniorEngineerPDA
    gloves: ClothingHandsGlovesColorYellow
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltChiefEngineerFilled
    ears: ClothingHeadsetEngineering
  innerClothingSkirt: ClothingUniformJumpskirtSeniorEngineer
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
