- type: job
  id: LinerServiceWorker
  name: работник Лайнера
  description: Сегодня они работают на Вас.
  playTimeTracker: JobLinerServiceWorker
  startingGear: ServiceWorkerGear
  icon: "JobIconServiceWorker"
  supervisors: job-supervisors-service
  canBeAntag: false
  access:
  - Service
  - Maintenance
  - Bar
  - Kitchen
  extendedAccess:
  - Hydroponics

- type: startingGear
  id: LinerServiceWorkerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBartender
    back: ClothingBackpackFilled
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesBootsLaceup
    belt: BoxFolderClipboard
    id: ServiceWorkerPDA
    ears: ClothingHeadsetService
  innerClothingSkirt: ClothingUniformJumpskirtBartender
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
