- type: job
  id: LinerServiceWorker
  name: service worker
  description: The service worker.
  playTimeTracker: JobLinerServiceWorker
  startingGear: DoctorGear
  supervisors: job-supervisors-service
  canBeAntag: false
  access:
  - Service
  - Maintenance
  - Bar
  - Kitchen
  extendedAccess:
  - Hydroponics
