- type: job
  id: LinerTech
  name: техник
  description: Trust him, he is engineer.
  playTimeTracker: JobLinerTech
  startingGear: LinerTechGear
  icon: "JobIconStationEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  extendedAccess:
  - Atmospherics

- type: startingGear
  id: LinerTechGear
  equipment:
    head: ClothingHeadHatBeretEngineering
    jumpsuit: ClothingUniformJumpsuitEngineering
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterVestHazard
    gloves: ClothingHandsGlovesColorYellow
    id: EngineerPDA
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  innerClothingSkirt: ClothingUniformJumpskirtEngineering
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
