- type: job
  id: LinerTech
  name: liner tech
  description: The liner tech.
  playTimeTracker: JobLinerTech
  startingGear: DoctorGear
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  extendedAccess:
  - Atmospherics
