- type: job
  id: BlueShieldOfficer
  name: job-name-blue-shield-officer
  description: job-description-blue-shield-officer
  playTimeTracker: JobBlueShieldOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Booster
      time: 10000000
  startingGear: BlueShieldOfficerGear
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  weight: 15
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Cargo
  - Atmospherics
  - Medical
  - HeadOfSecurity
  - ResearchDirector
  - ChiefMedicalOfficer
  - ChiefEngineer
  - Quartermaster

- type: startingGear
  id: BlueShieldOfficerGear
  equipment:
    # TODO: blue shield officer gear
    jumpsuit: ClothingUniformJumpsuitBSO
    back: ClothingBackpackBlueShieldOfficerFilled # TODO
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSunglasses
    head: ClothingHeadHatBeretBso
    outerClothing: ClothingOuterArmorBSOCarapace
    id: HoPPDA
    ears: ClothingHeadsetAltCommand
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponRevolverMateba
    pocket2: HandheldCrewMonitor
    gloves: ClothingHandsGlovesCombat
  satchel: ClothingBackpackSatchelBlueShieldOfficerFilled
  duffelbag: ClothingBackpackDuffelBlueShieldOfficerFilled
