# event

- type: playTimeTracker
  id: JobLinerCaptain

- type: playTimeTracker
  id: JobLinerCaptainAssistant

- type: playTimeTracker
  id: JobLinerBoatswain

- type: playTimeTracker
  id: JobLinerSeniorTech

- type: playTimeTracker
  id: JobLinerTech

- type: playTimeTracker
  id: JobLinerOfficer

- type: playTimeTracker
  id: JobLinerDoctor

- type: playTimeTracker
  id: JobLinerGuest

- type: playTimeTracker
  id: JobLinerServiceWorker

- type: playTimeTracker
  id: JobLinerSanta
